### PR TITLE
Create devcontainer.json

### PR DESCRIPTION
**Pull request by Xo734**

### CODE REVIEW

**Comment by DanWin** [comment]
Hello @Xo734 ,

thanks for your contribution. What exactly is the purpose of this though?

**Comment by otn-sein** [comment]
hey i bought sum from robot money and havent received my payment on paypal

**Comment by DanWin** [comment]
Hello @otn-sein , this is a software development issue tracker. You can report software problems or feature requests here related to le-chat-php, a chat software I wrote. This is not a discussion forum about darknet scammers. Sorry for your loss, but you won't find what you are looking for, because ALL of these type of sites are scams. Nobody will give you more money in exchange for less, that's not how the world works.

**Comment by DanWin** [comment]
Seems to be useless, it's a general purpose docker image by microsoft with many programming languages bundled and only available for x86-64 architecture.

**Pull request closed without merging**
