### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abhishek213-alb**
Improved readbility

### CODE REVIEW

**Comment by rexzooly** [comment]
You have removed caps where they should be this change already is incorrect when also PHP is the Correct way of doing it I don't find this change a improvement. you have also removed Caps from names this is also incorrect.

I do like the fact of the pointers but a lot of it you have incorrectly changed.

**Comment by abhishek213-alb** [comment]
@rexzooly let me modify once

**Review by abhishek213-alb — COMMENTED** [review]
Updated

**Comment by abhishek213-alb** [comment]
@rexzooly Mam please check once

**Comment by rexzooly** [comment]
Now you have caps where they shouldn't be like "Clone The", Clone was the start so it would be "Clone the" 

I believe the original was fine as it was, I been using it on and off for years and never had a problem right now I am not sure why you made these changes, Also looking at the Read Me as it is the first part isn't meant to be in bullet points.

Why did you feel it didn't read correctly? I believe this merge myself is un-needed and in places incorrect.

**Comment by DanWin** [comment]
@abhishek213-alb Thanks for your contribution, but as discussed above, this is just incorrect change of capitalization. Thus I'm closing this pull request.

**Pull request closed without merging**
